name: webIDE2.0

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "1001:1001"  # Exposes backend on port 1001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Access to Docker engine
      - ../CollabrativeWebIDE/BaseImage/:/home/BaseImage/
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock # Docker engine socket
    networks:
      - app_network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Exposes frontend on port 1000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  playground_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "D:/Project/CollabrativeWebIDE/"