# Start from Node image
FROM node:20-alpine3.19

# Install dependencies required for building native modules
RUN apk add --no-cache python3 make g++

# Set up the React App
WORKDIR /app
COPY ReactApp/package*.json ./
RUN npm install
COPY ReactApp/ .

# Set up the runner (Node.js backend for specific commands)
WORKDIR /home/runner
COPY runner/package*.json ./
RUN npm install
COPY runner/ .

# Expose port and set the command
EXPOSE 1000
EXPOSE 3000
CMD ["npm", "run", "dev"]